/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#f0f7ff',
          100: '#e0effe',
          200: '#bae0fd',
          300: '#7cc8fb',
          400: '#adc6ff',
          500: '#4d8eff',
          600: '#005ac2',
          700: '#004395',
          800: '#002e6a',
          900: '#001a42',
          950: '#0a0e18',
        },
        slate: {
          850: '#171b26',
          900: '#0f131d',
          950: '#0a0e18',
        },
        background: '#0f131d',
        surface: '#0f131d',
        'surface-dim': '#0f131d',
        'surface-bright': '#353944',
        'surface-container-lowest': '#0a0e18',
        'surface-container-low': '#171b26',
        'surface-container': '#1c1f2a',
        'surface-container-high': '#262a35',
        'surface-container-highest': '#313540',
        'surface-variant': '#313540',
        'on-surface': '#dfe2f1',
        'on-surface-variant': '#c2c6d6',
        'on-background': '#dfe2f1',
        primary: '#adc6ff',
        'primary-container': '#4d8eff',
        'on-primary': '#002e6a',
        'on-primary-container': '#00285d',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        secondary: '#d0bcff',
        'secondary-container': '#571bc1',
        'on-secondary': '#3c0091',
        'on-secondary-container': '#c4abff',
        tertiary: '#4edea3',
        'tertiary-container': '#00a572',
        'on-tertiary': '#003824',
        'on-tertiary-container': '#00311f',
        'tertiary-fixed': '#6ffbbe',
        outline: '#8c909f',
        'outline-variant': '#424754',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'inverse-surface': '#dfe2f1',
        'inverse-on-surface': '#2c303b',
        'inverse-primary': '#005ac2',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        '3xl': '1rem',
        full: '0.75rem',
      },
      spacing: {
        'space-xxs': '0.125rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-base': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'gutter-mobile': '1rem',
        'gutter-desktop': '1.5rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'headline-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-data': ['JetBrains Mono', 'monospace'],
        'label-caps': ['Inter', 'sans-serif'],
        'display-kpi': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-sm': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-data': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-kpi': ['44px', { lineHeight: '52px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'display-kpi-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
